POST http://localhost:5000/api/user/login
Content-Type: application/json

{
  "email": "info.stravix@gmail.com",
  "password": "Saurabh@123"
}


### Create a course (admin/instructor only)
POST http://localhost:5000/api/courses
Authorization: Bearer token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MzU3N2Q0MzZmYjI5YzE4ZWM0MDU0ZCIsImlhdCI6MTc0ODY4MzMyNCwiZXhwIjoxNzQ5Mjg4MTI0fQ.8YJ7ze2A1LL4r4ILs4YFWB1_joR8vqSOOjOD-rBEpf0
Content-Type: application/json

{
  "title": "Bundle 4",
  "slug": "bundle-4",
  "category": "Sales",
  "price": 11999,
  "discountedPrice": 9999,
  "description": "trading 101",
  "affiliateCommissionPercent": 30,
  "tags": ["trading", "marketing", "sales"],
  "status": "published",
  "youtubePlaylistId": "PLv9O1ieIsEgEXAMPLE"
}

### Upload Course Thumbnail
PUT http://localhost:5000/api/courses/683aca52e48c8eef9afdd31b/thumbnail
Authorization: Bearer token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MzU3N2Q0MzZmYjI5YzE4ZWM0MDU0ZCIsImlhdCI6MTc0ODc3Njc1NSwiZXhwIjoxNzQ5MzgxNTU1fQ.MBlz3NpC8qXjwildFzN6yHuoxJHwJ4gQ6G3v3YSkPlA

Content-Type: multipart/form-data; boundary=----MyCustomBoundary

------MyCustomBoundary
Content-Disposition: form-data; name="thumbnail"; filename="bundle-1.jpg"
Content-Type: image/jpeg

< ./bundle-1.jpg
------MyCustomBoundary--


### Get All Courses
GET http://localhost:5000/api/courses


### Upload thumbnail for "Bundle 1"
PUT http://localhost:5000/api/courses/683aca52e48c8eef9afdd31b/thumbnail
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4MzU3N2Q0MzZmYjI5YzE4ZWM0MDU0ZCIsImlhdCI6MTc0ODcxMjUwOSwiZXhwIjoxNzQ5MzE3MzA5fQ.LTeu-uqgPl3Lp61aODrpJ4-ui2gEfQZoopr2iqiZxuU

Content-Type: multipart/form-data; boundary=----CustomBoundary999

------CustomBoundary999
Content-Disposition: form-data; name="thumbnail"; filename="bundle-1.jpg"
Content-Type: image/jpeg

< ./bundle-1.jpg
------CustomBoundary999--



### Enroll user into related courses manually (admin)
POST http://localhost:5000/api/admin/enroll-related-courses
Content-Type: application/json
Cookie: stravix-auth-token=your_admin_jwt_token_here

{
  "userId": "replace_with_user_id",
  "courseId": "replace_with_main_bundle_course_id"
}
